#mixed-port: 7890
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: '0.0.0.0:9090'
secret: 123456
external-ui: '/root/clash-dashboard'
dns:
  enable: true
  nameserver:
    - 223.15.124.75
    - 119.219.233.219
rule-providers:
  yiyuanjichang:
    behavior: "domain" # domain, ipcidr or classical (premium core only)
    type: https
    url: ""
    # format: 'yaml' # or 'text'
    interval: 3600
    path: ./yiyuanjichang.yaml
rules:
  - RULE-SET,apple,REJECT
